/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeDialog: typeof import('./src/components/CodeDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewReferralDialog: typeof import('./src/components/NewReferralDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
