/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeDialog: typeof import('./src/components/CodeDialog.vue')['default']
    FeedControls: typeof import('./src/components/FeedControls.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewReferralDialog: typeof import('./src/components/NewReferralDialog.vue')['default']
    ProgramAutocomplete: typeof import('./src/components/ProgramAutocomplete.vue')['default']
    ProgramControls: typeof import('./src/components/ProgramControls.vue')['default']
    PromotionAd: typeof import('./src/components/PromotionAd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendingProgramsSlider: typeof import('./src/components/TrendingProgramsSlider.vue')['default']
  }
}
